#!/usr/bin/env python3
"""
render_onepagers.py — emit the two shareable one-pagers as brand SVGs.

Derived artifacts: reports/figures/onepager-*.svg are generated by this script;
numbers come from reports/RESULTS.md (verified against runs/). Regenerate with:

    python3 scripts/render_onepagers.py --overwrite

Layout is 1080x1350 (4:5 portrait — LinkedIn feed image). Palette/typography are
shared with scripts/render_results_figures.py. Stdlib only, deterministic.
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from render_results_figures import MONO, OUT_DIR, P, SANS, SERIF, esc, rbar, svg, text

W, H = 1080, 1350
MARGIN = 64
SITE = "barbhs.com/blog/measuring-pageindex"


def wrap(s: str, width: int) -> list[str]:
    lines, cur = [], ""
    for word in s.split():
        cand = f"{cur} {word}".strip()
        if len(cand) <= width:
            cur = cand
        else:
            lines.append(cur)
            cur = word
    if cur:
        lines.append(cur)
    return lines


def para(x, y, s, width, size=14.5, fill=P["text"], leading=21, weight=None):
    out = []
    for i, line in enumerate(wrap(s, width)):
        out.append(text(x, y + i * leading, line, size=size, fill=fill, weight=weight))
    return out, y + len(wrap(s, width)) * leading


def header(title, subtitle):
    return [
        text(MARGIN, 96, title, size=44, fill=P["ink"], weight=600, family=SERIF),
        text(MARGIN, 132, subtitle, size=17.5, fill=P["muted"]),
    ]


def footer(line):
    y = H - 56
    return [
        f'<line x1="{MARGIN}" y1="{y - 26}" x2="{W - MARGIN}" y2="{y - 26}" stroke="{P["grid"]}" stroke-width="1.5"/>',
        text(MARGIN, y, line, size=13.5, fill=P["muted"]),
        text(W - MARGIN, y, SITE, size=13.5, fill=P["cobalt"], anchor="end", weight=600),
    ]


# --------------------------------------------------------------------------
# One-pager 1 — The Four-Stage Autopsy
# --------------------------------------------------------------------------

STAGES = [
    ("1 · REPRESENTATION",
     "The material the tool receives: extraction, headings, boundaries, glyphs.",
     "PDF extraction turned p<.001 into pB.001 — 39 corrupted statistics in one "
     "paper, visible before a single retrieval run.",
     "Diff the extracted text against the source. Sample the numbers, symbols, and "
     "ligatures — before anything downstream runs."),
    ("2 · TREE",
     "The navigational map built over the document.",
     "An LLM-inferred tree cost $6.44 and dropped the section numbers the questions "
     "keyed on. The PDF's own embedded outline was free and matched the authored "
     "headings 311 / 311.",
     "Open the index. Count copied, empty, and duplicated fields. Check authored "
     "headings and bookmarks before paying to infer structure."),
    ("3 · NAVIGATION",
     "Which branches the agent follows — and what it actually fetches.",
     "A local 7B model read the tree, fetched nothing, and wrote fluent answers "
     "anyway — in 15 of 28 runs. Fluency did not reveal the failure; the tool "
     "trace did.",
     "Save tool traces. Score “did it fetch the sections the answer needs” "
     "separately from the answer itself."),
    ("4 · SYNTHESIS",
     "The final answer composed from whatever was fetched.",
     "One page said 13 years, another said 14. One model reported the discrepancy; "
     "another smoothed it into a single clean number.",
     "Grade grounding, not fluency. Check that conflicts and absences survive into "
     "the answer instead of being polished away."),
]


def onepager_autopsy():
    body = header("The Four-Stage Autopsy",
                  "Where retrieval failures actually live — and what to open to find them")
    # flow strip
    chip_w, chip_h, gap = 216, 46, 40
    total = 4 * chip_w + 3 * gap
    x = (W - total) / 2
    y = 168
    names = ["representation", "tree", "navigation", "synthesis"]
    for i, name in enumerate(names):
        cx = x + i * (chip_w + gap)
        body.append(f'<rect x="{cx:g}" y="{y}" width="{chip_w}" height="{chip_h}" rx="10" '
                    f'fill="{P["panel"]}" stroke="{P["primary"]}" stroke-width="2.5"/>')
        body.append(text(cx + chip_w / 2, y + 29, name, size=17, fill=P["ink"],
                         anchor="middle", weight=600))
        if i < 3:
            ax = cx + chip_w + gap / 2
            body.append(text(ax, y + 30, "→", size=22, fill=P["muted"], anchor="middle"))
    body.append(text(W / 2, y + 78,
                     "A wrong answer is four possible failures wearing one disguise. "
                     "Give each somewhere to land.",
                     size=15, fill=P["text"], anchor="middle"))

    # cards
    card_x, card_w = MARGIN, W - 2 * MARGIN
    card_h, card_gap = 226, 18
    y = 290
    col2_x = card_x + 34
    col3_x = card_x + card_w / 2 + 30
    col_chars = 52
    for name, definition, failure, check in STAGES:
        body.append(f'<rect x="{card_x}" y="{y}" width="{card_w}" height="{card_h}" rx="14" '
                    f'fill="{P["panel"]}" stroke="{P["grid"]}"/>')
        body.append(f'<path d="M{card_x},{y + 14} a14,14 0 0 1 14,-14 h-8 z" fill="none"/>')
        body.append(f'<rect x="{card_x}" y="{y + 16}" width="6" height="{card_h - 32}" rx="3" '
                    f'fill="{P["primary"]}"/>')
        body.append(text(col2_x, y + 40, name, size=20, fill=P["ink"], weight=700))
        seg, _ = para(col2_x, y + 68, definition, 100, size=14.5, fill=P["muted"])
        body += seg
        label_y = y + 104
        body.append(text(col2_x, label_y, "FAILURE SEEN IN THE STUDY", size=11.5,
                         fill=P["primary"], weight=700, style='letter-spacing="1.2"'))
        seg, _ = para(col2_x, label_y + 24, failure, col_chars, size=14, leading=20)
        body += seg
        body.append(text(col3_x, label_y, "WHAT TO OPEN AND CHECK", size=11.5,
                         fill=P["cobalt"], weight=700, style='letter-spacing="1.2"'))
        seg, _ = para(col3_x, label_y + 24, check, col_chars, size=14, leading=20)
        body += seg
        y += card_h + card_gap
    body += footer("From an 11-run measurement study of PageIndex · every number "
                   "traceable to a run artifact")
    return svg(W, H, body)


# --------------------------------------------------------------------------
# One-pager 2 — The Tree Tax
# --------------------------------------------------------------------------

def tree_glyph(x, y, s=1.0, color=None):
    """Small document-tree icon: root bar + two indented child bars + leaves."""
    c = color or P["ink"]
    rows = [(0, 26), (10, 20), (10, 20), (20, 14)]
    out = []
    for i, (indent, w) in enumerate(rows):
        out.append(f'<rect x="{x + indent * s:g}" y="{y + i * 9 * s:g}" '
                   f'width="{w * s:g}" height="{4.5 * s:g}" rx="{2 * s:g}" fill="{c}"/>')
    return out


def onepager_treetax():
    body = header("The Tree Tax",
                  "The recurring RAG cost that never shows up in the demo")

    # --- the loop diagram -------------------------------------------------
    y0 = 196
    body.append(text(MARGIN, y0, "Vectorless RAG sends the agent a tree of the document. "
                                 "The tree stays in context —", size=16, fill=P["text"]))
    body.append(text(MARGIN, y0 + 26, "so every later turn re-bills it as input.",
                     size=16, fill=P["text"], weight=600))

    turn_w, turn_h, tgap = 200, 132, 50
    total = 4 * turn_w + 3 * tgap
    tx = (W - total) / 2
    ty = y0 + 66
    labels = ["turn 1", "turn 2", "turn 3", "turn n"]
    sub = ["read the tree", "fetch a section", "fetch another", "answer"]
    for i, (lab, s) in enumerate(zip(labels, sub)):
        cx = tx + i * (turn_w + tgap)
        body.append(f'<rect x="{cx:g}" y="{ty}" width="{turn_w}" height="{turn_h}" rx="12" '
                    f'fill="{P["panel"]}" stroke="{P["grid"]}" stroke-width="1.5"/>')
        body.append(text(cx + 18, ty + 34, lab, size=17, fill=P["ink"], weight=700))
        body.append(text(cx + 18, ty + 58, s, size=14, fill=P["muted"]))
        body += tree_glyph(cx + 18, ty + 78, 1.1, P["primary"])
        body.append(text(cx + 64, ty + 100, "+ tree, again", size=13.5, fill=P["primary"],
                         weight=600))
        if i < 3:
            ax = cx + turn_w + tgap / 2
            body.append(text(ax, ty + turn_h / 2 + 7, "→", size=24, fill=P["muted"],
                             anchor="middle"))
    # formula strip
    fy = ty + turn_h + 70
    body.append(f'<rect x="{MARGIN}" y="{fy - 36}" width="{W - 2 * MARGIN}" height="56" rx="10" '
                f'fill="#F0EBDF"/>')
    body.append(text(W / 2, fy, "tree tokens  ×  turns per question  ×  questions  "
                                "=  recurring input cost", size=17, fill=P["ink"],
                     anchor="middle", weight=600, family=MONO))

    # --- measured tree sizes ----------------------------------------------
    sy = fy + 92
    body.append(text(MARGIN, sy, "How big is the tree? (same 339-node website corpus)",
                     size=19, fill=P["ink"], weight=600, family=SERIF))
    bars = [
        ("headings only", 8934, P["cobalt"], "8.9K tokens"),
        ("real summaries on every node", 35516, P["primary"], "35.5K"),
        ("“add summaries” default — 80% verbatim copies", 43730, P["primary"], "43.7K"),
    ]
    bx0, bx1 = MARGIN, W - MARGIN - 150
    sx = (bx1 - bx0) / 45000
    by = sy + 30
    for lab, v, color, vlab in bars:
        bw = v * sx
        body.append(rbar(bx0, by, bw, 30, color))
        full = f"{vlab} · {lab}"
        if bx0 + bw + 12 + 7.2 * len(full) > W - MARGIN:
            body.append(text(bx0 + bw - 14, by + 21, full, size=14, fill=P["ground"],
                             anchor="end", weight=600))
        else:
            body.append(text(bx0 + bw + 12, by + 21, full, size=14, fill=P["text"]))
        by += 46
    body.append(text(MARGIN, by + 16, "The default was the largest artifact of every "
                                      "condition built — a feature that mostly wasn't "
                                      "running, billed on every turn.",
                     size=14.5, fill=P["muted"]))

    # --- measured cost -----------------------------------------------------
    cy = by + 76
    body.append(text(MARGIN, cy, "What it cost (measured, same questions, same navigator)",
                     size=19, fill=P["ink"], weight=600, family=SERIF))
    stat_w = (W - 2 * MARGIN - 24) / 2
    for i, (corpus, low, high, mult) in enumerate([
            ("Website · 14 questions", "$0.80", "$3.29", "4.1×"),
            ("RFC 9110 · 24 questions", "$1.30", "$6.01", "4.6×")]):
        cx = MARGIN + i * (stat_w + 24)
        body.append(f'<rect x="{cx:g}" y="{cy + 22}" width="{stat_w:g}" height="140" rx="14" '
                    f'fill="{P["panel"]}" stroke="{P["grid"]}"/>')
        body.append(text(cx + 26, cy + 54, corpus, size=15, fill=P["muted"], weight=600))
        body.append(text(cx + 26, cy + 104, low, size=34, fill=P["cobalt"], weight=700))
        body.append(text(cx + 26, cy + 130, "headings tree", size=13, fill=P["muted"]))
        body.append(text(cx + stat_w / 2 + 14, cy + 104, high, size=34, fill=P["primary"],
                         weight=700))
        body.append(text(cx + stat_w / 2 + 14, cy + 130, f"summary tree · {mult}",
                         size=13, fill=P["muted"]))

    # --- closing takeaway ---------------------------------------------------
    ky = cy + 210
    body.append(f'<rect x="{MARGIN}" y="{ky}" width="{W - 2 * MARGIN}" height="118" rx="14" '
                f'fill="{P["panel"]}" stroke="{P["grid"]}"/>')
    body.append(f'<rect x="{MARGIN}" y="{ky + 16}" width="6" height="86" rx="3" '
                f'fill="{P["primary"]}"/>')
    body.append(text(MARGIN + 34, ky + 48, "Index-build cost is a one-time line item "
                                           "everyone sees. The re-sent tree is the cost "
                                           "nobody prices.",
                     size=17, fill=P["ink"], weight=600))
    body.append(text(MARGIN + 34, ky + 82, "Before enriching an index, price the "
                                           "enrichment times every turn it will ride "
                                           "along on.",
                     size=15, fill=P["text"]))

    body += footer("Structure tokens & costs from recorded runs · details in the "
                   "consolidated results")
    return svg(W, H, body)


PAGES = {
    "onepager-four-stage-autopsy.svg": onepager_autopsy,
    "onepager-tree-tax.svg": onepager_treetax,
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--overwrite", action="store_true",
                    help="required to replace existing files")
    args = ap.parse_args()
    for name, fn in PAGES.items():
        path = os.path.join(OUT_DIR, name)
        if os.path.exists(path) and not args.overwrite:
            print(f"refusing to overwrite {path} (pass --overwrite)", file=sys.stderr)
            return 1
        with open(path, "w", encoding="utf-8") as f:
            f.write(fn())
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
